import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-family-sans)"],
        mono: ["var(--font-family-mono)"],
        serif: ["var(--font-family-serif)"],
      },
      fontSize: {
        xs: ["var(--font-size-xs)", { lineHeight: "var(--line-height-tight)" }],
        sm: ["var(--font-size-sm)", { lineHeight: "var(--line-height-snug)" }],
        base: ["var(--font-size-base)", { lineHeight: "var(--line-height-normal)" }],
        lg: ["var(--font-size-lg)", { lineHeight: "var(--line-height-normal)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--line-height-snug)" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--line-height-tight)" }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--line-height-tight)" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--line-height-none)" }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--line-height-none)" }],
        "6xl": ["var(--font-size-6xl)", { lineHeight: "var(--line-height-none)" }],
        "7xl": ["var(--font-size-7xl)", { lineHeight: "var(--line-height-none)" }],
        "8xl": ["var(--font-size-8xl)", { lineHeight: "var(--line-height-none)" }],
        "9xl": ["var(--font-size-9xl)", { lineHeight: "var(--line-height-none)" }],
      },
      spacing: {
        "0": "var(--spacing-0)",
        "px": "var(--spacing-px)",
        "0.5": "var(--spacing-0-5)",
        "1": "var(--spacing-1)",
        "1.5": "var(--spacing-1-5)",
        "2": "var(--spacing-2)",
        "2.5": "var(--spacing-2-5)",
        "3": "var(--spacing-3)",
        "3.5": "var(--spacing-3-5)",
        "4": "var(--spacing-4)",
        "5": "var(--spacing-5)",
        "6": "var(--spacing-6)",
        "7": "var(--spacing-7)",
        "8": "var(--spacing-8)",
        "9": "var(--spacing-9)",
        "10": "var(--spacing-10)",
        "11": "var(--spacing-11)",
        "12": "var(--spacing-12)",
        "14": "var(--spacing-14)",
        "16": "var(--spacing-16)",
        "20": "var(--spacing-20)",
        "24": "var(--spacing-24)",
        "28": "var(--spacing-28)",
        "32": "var(--spacing-32)",
        "36": "var(--spacing-36)",
        "40": "var(--spacing-40)",
        "44": "var(--spacing-44)",
        "48": "var(--spacing-48)",
        "52": "var(--spacing-52)",
        "56": "var(--spacing-56)",
        "60": "var(--spacing-60)",
        "64": "var(--spacing-64)",
        "72": "var(--spacing-72)",
        "80": "var(--spacing-80)",
        "96": "var(--spacing-96)",
      },
      colors: {
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
        },
        success: {
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
        },
        warning: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
        },
        error: {
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
        },
        info: {
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
          950: "var(--color-info-950)",
        },
        background: {
          primary: "var(--color-background-primary)",
          secondary: "var(--color-background-secondary)",
          tertiary: "var(--color-background-tertiary)",
          elevated: "var(--color-background-elevated)",
          overlay: "var(--color-background-overlay)",
        },
        surface: {
          primary: "var(--color-surface-primary)",
          secondary: "var(--color-surface-secondary)",
          tertiary: "var(--color-surface-tertiary)",
          hover: "var(--color-surface-hover)",
          pressed: "var(--color-surface-pressed)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
          link: "var(--color-text-link)",
          "link-hover": "var(--color-text-link-hover)",
        },
        border: {
          primary: "var(--color-border-primary)",
          secondary: "var(--color-border-secondary)",
          tertiary: "var(--color-border-tertiary)",
          focus: "var(--color-border-focus)",
          error: "var(--color-border-error)",
          success: "var(--color-border-success)",
          warning: "var(--color-border-warning)",
        },
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        inner: "var(--shadow-inner)",
        focus: "var(--shadow-focus)",
        none: "var(--shadow-none)",
        primary: "var(--shadow-primary)",
        secondary: "var(--shadow-secondary)",
        success: "var(--shadow-success)",
        warning: "var(--shadow-warning)",
        error: "var(--shadow-error)",
        info: "var(--shadow-info)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        moderate: "var(--duration-moderate)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
        slowest: "var(--duration-slowest)",
      },
      transitionTimingFunction: {
        smooth: "var(--easing-smooth)",
        bounce: "var(--easing-bounce)",
        spring: "var(--easing-spring)",
        sharp: "var(--easing-sharp)",
        emphasized: "var(--easing-emphasized)",
      },
      animation: {
        "fade-in": "var(--animation-fade-in)",
        "fade-out": "var(--animation-fade-out)",
        "slide-up": "var(--animation-slide-up)",
        "slide-down": "var(--animation-slide-down)",
        "slide-left": "var(--animation-slide-left)",
        "slide-right": "var(--animation-slide-right)",
        "scale-up": "var(--animation-scale-up)",
        "scale-down": "var(--animation-scale-down)",
        bounce: "var(--animation-bounce)",
        pulse: "var(--animation-pulse)",
        spin: "var(--animation-spin)",
      },
    },
  },
  plugins: [
    function ({ addUtilities, addComponents }) {
      // Semantic Component Utilities
      addComponents({
        '.btn-base': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: '0.375rem',
          fontWeight: '500',
          transition: 'var(--transition-button)',
          cursor: 'pointer',
          '&:disabled': {
            opacity: '0.5',
            cursor: 'not-allowed',
          },
        },
        '.input-base': {
          width: '100%',
          borderRadius: '0.375rem',
          border: '1px solid var(--color-border-primary)',
          backgroundColor: 'var(--color-surface-primary)',
          color: 'var(--color-text-primary)',
          transition: 'var(--transition-input)',
          '&:focus': {
            outline: 'none',
            borderColor: 'var(--color-border-focus)',
            boxShadow: 'var(--shadow-focus)',
          },
          '&:disabled': {
            opacity: '0.5',
            cursor: 'not-allowed',
          },
        },
        '.card-base': {
          backgroundColor: 'var(--color-surface-primary)',
          borderRadius: '0.5rem',
          border: '1px solid var(--color-border-primary)',
          transition: 'var(--transition-card)',
        },
        '.modal-base': {
          backgroundColor: 'var(--color-background-elevated)',
          borderRadius: '0.5rem',
          boxShadow: 'var(--elevation-modal)',
          border: '1px solid var(--color-border-primary)',
        },
      });

      // Density Utilities
      addUtilities({
        '.density-compact': {
          '--button-height': 'var(--button-height-compact)',
          '--input-height': 'var(--input-height-compact)',
          '--card-padding': 'var(--card-padding-compact)',
          '--component-gap': 'var(--component-gap-compact)',
          '--icon-size': 'var(--icon-size-compact)',
        },
        '.density-comfortable': {
          '--button-height': 'var(--button-height-comfortable)',
          '--input-height': 'var(--input-height-comfortable)',
          '--card-padding': 'var(--card-padding-comfortable)',
          '--component-gap': 'var(--component-gap-comfortable)',
          '--icon-size': 'var(--icon-size-comfortable)',
        },
        '.density-spacious': {
          '--button-height': 'var(--button-height-spacious)',
          '--input-height': 'var(--input-height-spacious)',
          '--card-padding': 'var(--card-padding-spacious)',
          '--component-gap': 'var(--component-gap-spacious)',
          '--icon-size': 'var(--icon-size-spacious)',
        },
      });

      // Elevation Utilities
      addUtilities({
        '.elevation-0': { boxShadow: 'var(--elevation-0)' },
        '.elevation-1': { boxShadow: 'var(--elevation-1)' },
        '.elevation-2': { boxShadow: 'var(--elevation-2)' },
        '.elevation-3': { boxShadow: 'var(--elevation-3)' },
        '.elevation-4': { boxShadow: 'var(--elevation-4)' },
        '.elevation-5': { boxShadow: 'var(--elevation-5)' },
        '.elevation-6': { boxShadow: 'var(--elevation-6)' },
        '.elevation-surface': { boxShadow: 'var(--elevation-surface)' },
        '.elevation-card': { boxShadow: 'var(--elevation-card)' },
        '.elevation-button': { boxShadow: 'var(--elevation-button)' },
        '.elevation-dropdown': { boxShadow: 'var(--elevation-dropdown)' },
        '.elevation-modal': { boxShadow: 'var(--elevation-modal)' },
        '.elevation-overlay': { boxShadow: 'var(--elevation-overlay)' },
        '.elevation-popup': { boxShadow: 'var(--elevation-popup)' },
      });

      // Typography Scale Utilities
      addUtilities({
        '.text-display-large': { fontSize: 'var(--text-display-large)' },
        '.text-display-medium': { fontSize: 'var(--text-display-medium)' },
        '.text-display-small': { fontSize: 'var(--text-display-small)' },
        '.text-headline-large': { fontSize: 'var(--text-headline-large)' },
        '.text-headline-medium': { fontSize: 'var(--text-headline-medium)' },
        '.text-headline-small': { fontSize: 'var(--text-headline-small)' },
        '.text-title-large': { fontSize: 'var(--text-title-large)' },
        '.text-title-medium': { fontSize: 'var(--text-title-medium)' },
        '.text-title-small': { fontSize: 'var(--text-title-small)' },
        '.text-body-large': { fontSize: 'var(--text-body-large)' },
        '.text-body-medium': { fontSize: 'var(--text-body-medium)' },
        '.text-body-small': { fontSize: 'var(--text-body-small)' },
        '.text-label-large': { fontSize: 'var(--text-label-large)' },
        '.text-label-medium': { fontSize: 'var(--text-label-medium)' },
        '.text-label-small': { fontSize: 'var(--text-label-small)' },
      });

      // Spacing Utilities
      addUtilities({
        '.gap-component-xs': { gap: 'var(--spacing-component-xs)' },
        '.gap-component-sm': { gap: 'var(--spacing-component-sm)' },
        '.gap-component-md': { gap: 'var(--spacing-component-md)' },
        '.gap-component-lg': { gap: 'var(--spacing-component-lg)' },
        '.gap-component-xl': { gap: 'var(--spacing-component-xl)' },
        '.gap-component-2xl': { gap: 'var(--spacing-component-2xl)' },
        '.gap-section-xs': { gap: 'var(--spacing-section-xs)' },
        '.gap-section-sm': { gap: 'var(--spacing-section-sm)' },
        '.gap-section-md': { gap: 'var(--spacing-section-md)' },
        '.gap-section-lg': { gap: 'var(--spacing-section-lg)' },
        '.gap-section-xl': { gap: 'var(--spacing-section-xl)' },
        '.gap-page-xs': { gap: 'var(--spacing-page-xs)' },
        '.gap-page-sm': { gap: 'var(--spacing-page-sm)' },
        '.gap-page-md': { gap: 'var(--spacing-page-md)' },
        '.gap-page-lg': { gap: 'var(--spacing-page-lg)' },
        '.gap-page-xl': { gap: 'var(--spacing-page-xl)' },
      });
    },
  ],
} satisfies Config;
